Repository ravenrebel/UrbanDictionary, pull requests merged in 2020-04, with the labels that each got.

#6 Ih main page ui & another trash
  UrbanDictionary/ClientApp/src/app/app.component.html
  UrbanDictionary/ClientApp/src/app/components/add-new-word-component/add-new-word-component.component.css
  UrbanDictionary/ClientApp/src/app/components/add-new-word-component/add-new-word-component.component.html
  UrbanDictionary/ClientApp/src/app/components/footer-component/footer-component.component.html
  UrbanDictionary/ClientApp/src/app/components/header-component/header-component.component.html
  UrbanDictionary/ClientApp/src/app/components/home-page-component/home-page-component.component.css
  UrbanDictionary/ClientApp/src/app/components/home-page-component/home-page-component.component.html
  UrbanDictionary/ClientApp/src/app/components/random-word-component/random-word-component.component.css
  UrbanDictionary/ClientApp/src/app/components/random-word-component/random-word-component.component.html
  UrbanDictionary/ClientApp/src/app/components/sign-up-component/sign-up-component.component.css
  UrbanDictionary/ClientApp/src/app/components/sign-up-component/sign-up-component.component.html
  UrbanDictionary/ClientApp/src/app/components/top-words-component/top-words-component.component.html
  UrbanDictionary/ClientApp/src/app/img/bg-callout.jpg
  UrbanDictionary/ClientApp/src/app/img/bg-masthead.jpg
  UrbanDictionary/ClientApp/src/app/img/fonForWordOnMainPage.jpg
  UrbanDictionary/ClientApp/src/app/img/meeting.jpg
  UrbanDictionary/ClientApp/src/app/model/empty.spec.ts
  UrbanDictionary/ClientApp/src/app/model/empty.ts
  UrbanDictionary/ClientApp/src/app/model/tag-dto.spec copy.ts
  UrbanDictionary/ClientApp/src/app/model/tag-dto.ts
  UrbanDictionary/ClientApp/src/app/model/tag.ts
  UrbanDictionary/ClientApp/src/app/model/word-dto.spec.ts
  UrbanDictionary/ClientApp/src/app/model/word-dto.ts
  UrbanDictionary/ClientApp/src/app/model/word.ts
  UrbanDictionary/ClientApp/src/app/service/word.service.spec.ts
  UrbanDictionary/ClientApp/src/app/service/word.service.ts
  UrbanDictionary/ClientApp/src/index.html
  UrbanDictionary/ClientApp/src/styles.css
  UrbanDictionary/package-lock.json
Labels: enhancement

#7 Hot Fix img display
  UrbanDictionary/ClientApp/src/app/components/add-new-word-component/add-new-word-component.component.html
Labels: bug

#10 Rename BusinessLayer again, add CREATE, DELETE and GET by name to Wor…
  BusinessLayer/DTO/Mapper/IMapper.cs
  BusinessLayer/DTO/Mapper/TagServiceMapper.cs
  BusinessLayer/DTO/Mapper/WordServiceMapper.cs
  BusinessLayer/DTO/TagDTO.cs
  BusinessLayer/DTO/WordDTO.cs
  BusinessLayer/Services/Contracts/IServiceWrapper.cs
  BusinessLayer/Services/Contracts/ITagService.cs
  BusinessLayer/Services/Contracts/IUserService.cs
  BusinessLayer/Services/Contracts/IWordService.cs
  BusinessLayer/Services/ServiceWrapper.cs
  BusinessLayer/Services/TagService.cs
  BusinessLayer/Services/UserService.cs
  BusinessLayer/Services/WordService.cs
  BusinessLayer/UrbanDictionary.BusinessLayer.csproj
  BussinessLayer/Services/Contracts/ITagService.cs
  BussinessLayer/Services/Contracts/IUserService.cs
  BussinessLayer/Services/Contracts/IWordService.cs
  BussinessLayer/Services/WordService.cs
  DataAccess/Repositories/Contracts/IRepositoryBase.cs
  DataAccess/Repositories/Contracts/IRepositoryWrapper.cs
  DataAccess/Repositories/Contracts/ITagRepository.cs
  DataAccess/Repositories/Contracts/IWordRepository.cs
  DataAccess/Repositories/Contracts/IWordTagRepository.cs
  DataAccess/Repositories/RepositoryBase.cs
  DataAccess/Repositories/RepositoryWrapper.cs
  DataAccess/Repositories/TagRepository.cs
  DataAccess/Repositories/WordRepository.cs
  DataAccess/Repositories/WordTagRepository.cs
  DataAccess/UrbanDictionary.DataAccess.csproj
  UrbanDictionary.sln
  UrbanDictionary/ClientApp/src/app/components/random-word-component/random-word-component.component.ts
  UrbanDictionary/ClientApp/src/app/service/word.service.ts
  UrbanDictionary/Controllers/UserController.cs
  UrbanDictionary/Controllers/WordController.cs
  UrbanDictionary/Startup.cs
  UrbanDictionary/UrbanDictionary.csproj
Labels: bug, enhancement

#14 Ab server-Azure deployment
  BusinessLayer/Services/WordService.cs
  UrbanDictionary/.config/dotnet-tools.json
  UrbanDictionary/ClientApp/package-lock.json
  UrbanDictionary/ClientApp/package.json
  UrbanDictionary/ClientApp/src/app/service/word.service.ts
  UrbanDictionary/UrbanDictionary.csproj
  UrbanDictionary/appsettings.json
Labels: deployment
